image: gradle:jdk11-alpine

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - cd BookCase

stages:
  - build
  - test

cache:
  key: devtools-java-bookcase
  paths:
    - BookCase/.gradle/wrapper
    - BookCase/.gradle/caches
  policy: pull

build-job:
  stage: build
  script:
    - ./gradlew --build-cache assemble
  cache:
    key: devtools-java-bookcase
    paths:
      - BookCase/.gradle/wrapper
      - BookCase/.gradle/caches
    policy: push
  artifacts:
    paths:
      - BookCase/core/build/
      - BookCase/app/build/
    expire_in: 1 day

junit-job:
  stage: test
  dependencies:
    - build-job
  script:
    - ./gradlew test
  artifacts:
    paths:
        - BookCase/core/build/reports/tests
    expire_in: 1 day

checkstyle-job:
  stage: test
  dependencies:
    - build-job
  script:
    - ./gradlew checkstyleMain
    - ./gradlew checkstyleTest
  artifacts:
    paths:
        - BookCase/core/build/reports/checkstyle
        - BookCase/app/build/reports/checkstyle
    expire_in: 1 day

spotbugs-job:
  stage: test
  dependencies:
    - build-job
  script:
    - ./gradlew spotbugsMain
    - ./gradlew spotbugsTest
  artifacts:
    paths:
        - BookCase/core/build/reports/spotbugs
    expire_in: 1 day

jacoco-job:
  stage: test
  dependencies:
    - build-job
  script:
    - ./gradlew jacocoTestCoverageVerification
    - ./gradlew jacocoTestReport
  artifacts:
    paths:
        - BookCase/core/build/reports/jacoco
    expire_in: 1 day      